on:
  push:
    branches:
    - "master"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v1
      - name: Initialize Pull Request
        uses: gha-utilities/init-pull-request@v0.0.2
        with:
          pull_request_token: ${{ secrets.GITHUB_TOKEN }}
          head: master
          base: develop
          title: 'Merge master into develop'
          body: '' 
    
